# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt_ui/instructor_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(712, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(712, 655))
        Dialog.setMaximumSize(QtCore.QSize(712, 655))
        Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.lblName = QtWidgets.QLabel(self.groupBox_3)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.lblHours = QtWidgets.QLabel(self.groupBox_3)
        self.lblHours.setObjectName("lblHours")
        self.gridLayout.addWidget(self.lblHours, 0, 2, 1, 1)
        self.lineEditHours = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditHours.setObjectName("lineEditHours")
        self.gridLayout.addWidget(self.lineEditHours, 0, 3, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.tableSchedule = QtWidgets.QTableView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableSchedule.sizePolicy().hasHeightForWidth())
        self.tableSchedule.setSizePolicy(sizePolicy)
        self.tableSchedule.setObjectName("tableSchedule")
        self.verticalLayout.addWidget(self.tableSchedule)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFinish = QtWidgets.QPushButton(Dialog)
        self.btnFinish.setObjectName("btnFinish")
        self.horizontalLayout.addWidget(self.btnFinish)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblName.setBuddy(self.lineEditName)
        self.lblHours.setBuddy(self.lineEditHours)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditName, self.lineEditHours)
        Dialog.setTabOrder(self.lineEditHours, self.tableSchedule)
        Dialog.setTabOrder(self.tableSchedule, self.btnFinish)
        Dialog.setTabOrder(self.btnFinish, self.btnCancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Instructor"))
        self.groupBox_3.setTitle(_translate("Dialog", "Details"))
        self.lblName.setText(_translate("Dialog", "Name"))
        self.lblHours.setText(_translate("Dialog", "Available Hours"))
        self.btnFinish.setText(_translate("Dialog", "Finish"))
        self.btnFinish.setShortcut(_translate("Dialog", "Ctrl+S"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.btnCancel.setShortcut(_translate("Dialog", "Esc"))