# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt_ui/section_fa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(714, 864)
        Dialog.setMinimumSize(QtCore.QSize(714, 864))
        Dialog.setMaximumSize(QtCore.QSize(714, 16777215))
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 1, 2, 1)
        self.lblName_2 = QtWidgets.QLabel(Dialog)
        self.lblName_2.setObjectName("lblName_2")
        self.gridLayout.addWidget(self.lblName_2, 0, 0, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtSelectSubject = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSelectSubject.sizePolicy().hasHeightForWidth())
        self.txtSelectSubject.setSizePolicy(sizePolicy)
        self.txtSelectSubject.setObjectName("txtSelectSubject")
        self.verticalLayout_3.addWidget(self.txtSelectSubject)
        self.verticalLayout.addWidget(self.groupBox)
        self.treeSubjects = QtWidgets.QTreeView(Dialog)
        self.treeSubjects.setMinimumSize(QtCore.QSize(0, 0))
        self.treeSubjects.setHeaderHidden(False)
        self.treeSubjects.setObjectName("treeSubjects")
        self.verticalLayout.addWidget(self.treeSubjects)
        self.tableSchedule = QtWidgets.QTableView(Dialog)
        self.tableSchedule.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableSchedule.setMinimumSize(QtCore.QSize(694, 509))
        self.tableSchedule.setMaximumSize(QtCore.QSize(694, 509))
        self.tableSchedule.setObjectName("tableSchedule")
        self.verticalLayout.addWidget(self.tableSchedule)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFinish = QtWidgets.QPushButton(Dialog)
        self.btnFinish.setObjectName("btnFinish")
        self.horizontalLayout.addWidget(self.btnFinish)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.lblName_2.setBuddy(self.lineEditName)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditName, self.txtSelectSubject)
        Dialog.setTabOrder(self.txtSelectSubject, self.treeSubjects)
        Dialog.setTabOrder(self.treeSubjects, self.tableSchedule)
        Dialog.setTabOrder(self.tableSchedule, self.btnFinish)
        Dialog.setTabOrder(self.btnFinish, self.btnCancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblName_2.setText(_translate("Dialog", "نام گروه"))
        self.groupBox.setTitle(_translate("Dialog", "جست و جو در واحد ها"))
        self.txtSelectSubject.setPlaceholderText(_translate("Dialog", "جست و جو ..."))
        self.btnFinish.setText(_translate("Dialog", "ایجاد"))
        self.btnFinish.setShortcut(_translate("Dialog", "Ctrl+S"))
        self.btnCancel.setText(_translate("Dialog", "بستن"))